### ISSUE TITLE
Migrating to meteor(ite) v0.9.0

### ISSUE THREAD

**Issue by bkuri** [grandmore/meteor-winston-papertrail#2]
https://hackpad.com/Migrating-Apps-UfPrM192vSQ
https://hackpad.com/Add-Meteor-0.9-support-for-your-Existing-Packages-P0R7y1PiXlu

**Comment by rootedsoftware** [comment]
+1 here, would be great to have this

**Comment by edwardupton** [comment]
+1

**Comment by dandv** [comment]
Looks like Edward did it - https://github.com/edwardupton/meteor-winston-papertrail/. Maybe rm this repo now?
